name: Run Gen.py

on:
  workflow_dispatch:  # 仅保留手动触发方式
    
jobs:
  run-gen-py:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 允许推送更改
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        persist-credentials: false  # 不使用默认的 GITHUB_TOKEN

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'  # 可根据项目需求调整Python版本

    - name: Install dependencies
      run: |
        if [ -f requirements.txt ]; then
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        fi

    - name: Run gen.py
      run: |
        python gen.py

    - name: Commit and push changes
      env:
        PERSONAL_ACCESS_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
      run: |
        git config --global user.email "yangrenruiyrr@163.com"
        git config --global user.name "杨人瑞"
        git add .
        
        # 检查是否有变更需要提交
        if [ -n "$(git status --porcelain)" ]; then
          git commit -m "运行gen.py脚本（手动触发）"
          git push https://${PERSONAL_ACCESS_TOKEN}@github.com/${{ github.repository }}.git
        else
          echo "无变更可提交。"
        fi    
